### ISSUE TITLE
UnboundLocalError when trying to create a lambda

### ISSUE THREAD

**Issue by ghost** [ConceptJunkie/rpn#3]
`lambda x isprime` raise

```
Traceback (most recent call last):
  File "rpn.py", line 608, in <module>
    handleOutput( rpn( sys.argv[ 1 : ] ) )
  File "rpn.py", line 575, in rpn
    enterInteractiveMode( )
  File "rpn.py", line 270, in enterInteractiveMode
    valueList = evaluate( terms )
  File "rpn.py", line 109, in evaluate
    currentValueList[ -1 ].add( term )
UnboundLocalError: local variable 'currentValueList' referenced before assignment
```

**Comment by ConceptJunkie** [comment]
Wow.  Either I broke multiple things yesterday or this bug has been around for a while.   I'll try to take a look at this today, but I am on vacation and have a lunch reservation in about an hour.   :-)

**Comment by ConceptJunkie** [comment]
I'll be honest, I rarely use interactive mode and my unit tests currently don't cover it.

**Comment by ConceptJunkie** [comment]
I've been trying to reproduce this problem, but can't.  Can you give me a little more context for what you were trying to do, tuxcrafting?  Even if you were doing something wrong, it should crash like that.

p.s.  I'd like to join the discussion on the Nineteenth Byte, but you need 20 reputation to be able to post.   I'm really tickled that people have discovered my project.  Solving problems like the puzzles you guys are discussing is one my favorite things to do with rpn.  That and converting speeds to furlongs per fortnight.

**Comment by ghost** [comment]
I was in the interactive mode, and without the help, I didn't know how to call a lambda. Now the problem is semi fixed (I get `unexpected end of input in function definition` with this code, but the next command automatically fail with the same error)

**Comment by ConceptJunkie** [comment]
Do a git pull and the help should work.  You can always get help in non-interactive mode with:

rpn help <i>topic</i>

**Comment by ConceptJunkie** [comment]
I'm going to close this issue unless someone can show exactly how to reproduce it.
